Command Handler with subfolders
An-Idiots-Guide/guidebot pull request #6
Opened 2017-08-19 23:57 UTC by BannukDE

New to JS and GitHub, still thought you might want to look @it.

Hope everything attaches correctly ;)

OneSentenceDescription:
Recursive path search with 2-dimensional-array as return to get all #commands out of subfolders.

2017-08-20 19:15 UTC, BannukDE reviewed
Added a third commit for resolving errors and cleaningCode

2017-08-20 19:22 UTC, YorkAARGH commented
You removed a required definition of `props` on line 48 which will crash the bot, I'm currently consulting with @eslachance about this PR.

2017-08-21 14:57 UTC, BannukDE commented
Found a last "props" in line 65 needs to be attached to "client.props", also change "var CmdFiles" to "const CmdFiles" in line 47.

In addition all CmdFiles NEED to be in Subfolder.

2017-08-21 15:20 UTC, eslachance commented
Please move the commands back to the root `./commands/` and make them work from there, in order to ensure that *existing* bots wanting to update, do not crash. Also, these are not "Example" commands. Those are literal, working, useful commands that people can use. 

Do not confuse this repository with your own work space. If you want those commands to be moved in your bot, do it in your own fork, not in this repository.

2017-08-21 15:29 UTC, eslachance requested changes
That, and reverting the "examples" folder crap.

2017-08-21 15:29 UTC, eslachance commented on index.js
> +          client.props = require(`./commands/${d}/${f}`);
No. `client.props` is global, that's absolutely horrifyingly stupid. `const props` must be a LOCALLY SCOPED VAR. putting it on client makes no goddamn sense.

2017-08-21 15:29 UTC, eslachance commented on index.js
> +        try {
no no no no no no

Why are you adding a try/catch inside a try/catch. WHY.

2017-08-21 15:29 UTC, eslachance commented on index.js
> +  const cmdFiles = await client.pathwalker("./commands/");
Why add a function to the client if you're only going to use it once? You should only make functions that you're going to use multiple times.

2017-08-21 19:36 UTC, BannukDE commented
I can understand that it must be frustrating to read the code of someone bad. But either you could find a nicer way telling me that my code creates "Brain anorisms" or I will take my first sentence: "...thought you might want to look..." literally and will neither work nor correspond anymore, with you.

If you can find, how do you like the changes?
I think I changed every requested object.

2017-08-21 19:48 UTC, eslachance commented
I know you're trying to be helpful, and I appreciate the effort you want to make, however, you're simply reducing the quality of the code with your PR. You went from attaching a temporary variable to the client, to using readDirSync, which is **blocking**, instead of using promises. 

I'm going to have to close this PR, as it's currently going nowhere and will not be helpful to GuideBot.

2017-08-21 19:48 UTC, closed without merging