Create calc.js
An-Idiots-Guide/guidebot pull request #67
Opened 2018-11-04 09:40 UTC by optimistguy

this is the actual command file for the calculator command

2018-11-04 10:11 UTC, YorkAARGH requested changes
These changes should be done to be considered for merging, also please close [PR 66](https://github.com/AnIdiotsGuide/guidebot/pull/66) and commit the package change to this PR.

2018-11-04 10:11 UTC, YorkAARGH commented on commands/calc.js
> +var math = require('mathjs');
var? this is 2018, we don't use var

2018-11-04 10:11 UTC, YorkAARGH commented on commands/calc.js
> +const Discord = require("discord.js");
Why are you requiring Discord here and on line20?

2018-11-04 10:11 UTC, YorkAARGH commented on commands/calc.js
> +exports.run = (bot, message, args, command) => {
Please follow the variable labelling of the project, we do not use `bot`, we use `client`

2018-11-04 10:11 UTC, YorkAARGH commented on commands/calc.js
> +    let input = args.join(" ");
If you're not redefining the variable please change it to const

2018-11-04 10:11 UTC, YorkAARGH commented on commands/calc.js
> +    message.channel.send({
This should be on one line

2018-11-04 10:14 UTC, optimistguy commented on commands/calc.js
> +var math = require('mathjs');
I can change it

2018-11-04 10:59 UTC, kyranet commented on commands/calc.js
> +    })
Missing semicolon-

2018-11-04 12:13 UTC, Soumil07 commented
Tldr of all those reviews - follow linting rules and you should be fine.

2018-11-04 12:14 UTC, Soumil07 commented
EBWODP: You should also be stopping the case where a person does `?math sin` and math.eval sends the obscure function for sin.

2018-11-15 10:01 UTC, YorkAARGH commented
Closing due to inactivity

2018-11-15 10:01 UTC, closed without merging