reloading commands with their alias
An-Idiots-Guide/guidebot pull request #70
Opened 2018-12-24 00:40 UTC by Clemens-E

**Please describe the changes this PR makes and why it should be merged, as well as any and all proof of successful tests:**
allowing reloading of commands with their alias
credits to omer#0001 for locating and fixing the error before I pulled my fork
**Semantic versioning classification:**  
- [ ] This PR changes the framework's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to README, etc.

2019-01-30 00:12 UTC, AndrewJWin commented
This merge request is well over a month old. Either fix the Linting issues or close the merge.

2019-01-30 15:46 UTC, Clemens-E commented
> This merge request is well over a month old. Either fix the Linting issues or close the merge.

Sorry, forgot about this pr. :/

2019-02-12 21:05 UTC, AndrewJWin commented
![Proof](https://i.andrew-is.online/i/4brf0.png)
It does work, however I would recommend rewriting to tell the user _What_ command they reloaded.

I.e.

**-reload halp**
Would result with
 **\<ping>, The command ``help`` has been reloaded**

2019-04-14 15:02 UTC, AndrewJWin commented
@YorkAARGH This PR request has been waiting merge since Febuary 12th. Please attend to this, either merge or close.

2019-04-14 18:35 UTC, kyranet requested changes

2019-04-14 18:35 UTC, kyranet commented on modules/functions.js
> +    commandName = command.help.name;
btw if `command` is `undefined`, this will cause a TypeError.

2019-05-28 14:57 UTC, Clemens-E commented
If no owner wants to review, merge, close, or even recognize this pr in any way, I can close it.

2019-05-28 14:57 UTC, closed without merging